// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
	"time"
)

type Submission struct {
	InvID    string
	DocUid   string
	SubUid   string
	Accepted sql.NullInt64
	Status   sql.NullString
	LongID   sql.NullString
	UpsertAt time.Time
}
